version: '3'
services:
  # MySQL Database
  mysqldb:
    image: mysql
    container_name: mysqldb
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: achatdb
    ports:
      - 3306:3306
    volumes:
      - dockerAngularSpringDatabaseData:/var/lib/mysql
    networks:
      - back

  # Spring Boot Backend
  spring-backend:
    image: moez063719/achat_backend:latest  
    ports:
      - "8089:8089"
    depends_on:
      - mysqldb
    networks:
      - back

  # Angular Frontend
  angular-frontend:
    image: moez063719/achat_frontend:latest 
    ports:
      - "8099:80"
    depends_on:
      - spring-backend
    networks:
      - back

volumes:
  dockerAngularSpringDatabaseData:

networks:
  back:
  front:
