apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-angular-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: angular-app
  template:
    metadata:
      labels:
        app: angular-app
    spec:
      containers:
        - name: my-angular-app
          image: myacrrepo063719.azurecr.io/achat_frontend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8099
# service type loadbalancer
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: angular-app
    k8s-app: angular-app
  name: angular-app
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 80
  type: LoadBalancer
  selector:
    app: angular-app
